language: python
dist: trusty
notifications:
  email: false
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  #- "3.5"

before_install:
  # ---- git lfs
  - mkdir -p $HOME/bin
  - wget https://github.com/github/git-lfs/releases/download/v1.1.2/git-lfs-linux-amd64-1.1.2.tar.gz
  - tar xvfz git-lfs-linux-amd64-1.1.2.tar.gz
  - mv git-lfs-1.1.2/git-lfs $HOME/bin/git-lfs
  - export PATH=$PATH:$HOME/bin/

  # ---- conda
  # https://conda.io/docs/travis.html
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip numpy gdal=2.1.0 matplotlib scipy
    cython pillow nbconvert beautifulsoup4 scikit-learn joblib requests
  - source activate test-environment
  - export GDAL_DATA=$HOME/miniconda/envs/test-environment/share/gdal
  - pip install pytest
  - python setup.py install

install:
  # ---- rastercube_testdata
  - git clone https://github.com/terrai/rastercube_testdata.git $HOME/testdata
  - export RASTERCUBE_TEST_DATA=$HOME/testdata

script:
  - py.test

# See also https://github.com/ozak/georasters/blob/master/.travis.yml